export const LANGUAGES = [
  { id: 'en', name: 'English' },
  { id: 'bn', name: 'Bengali' },
  { id: 'es', name: 'Spanish' },
  { id: 'fr', name: 'French' },
  { id: 'id', name: 'Indonesian' },
  { id: 'ru', name: 'Russian' },
  { id: 'sv', name: 'Swedish' },
  { id: 'tr', name: 'Turkish' },
  { id: 'ur', name: 'Urdu' },
  { id: 'zh', name: 'Chinese' },
];

const chapterIndices = {
  en: require('../../assets/data/chapters/en/index.json'),
  bn: require('../../assets/data/chapters/bn/index.json'),
  es: require('../../assets/data/chapters/es/index.json'),
  fr: require('../../assets/data/chapters/fr/index.json'),
  id: require('../../assets/data/chapters/id/index.json'),
  ru: require('../../assets/data/chapters/ru/index.json'),
  sv: require('../../assets/data/chapters/sv/index.json'),
  tr: require('../../assets/data/chapters/tr/index.json'),
  ur: require('../../assets/data/chapters/ur/index.json'),
  zh: require('../../assets/data/chapters/zh/index.json'),
};

export const getChapterIndex = (lang) => {
  return chapterIndices[lang] || chapterIndices['en'];
};

export const LOCALIZED_STRINGS = {
  en: {
    quranChapters: 'Quran Chapters',
    verses: 'Verses',
    settings: 'Settings',
    translationLanguage: 'Translation Language',
    readingFontSize: 'Reading Font Size',
    fontSizeDesc: 'Adjust the size of Arabic and translation text',
    preview: 'Preview',
    appInformation: 'App Information',
    version: 'Version',
    developer: 'Developer',
    bismillahTranslation: 'In the name of Allah, the Entirely Merciful, the Especially Merciful',
    showTransliteration: 'Show Transliteration',
    transliterationDesc: 'Display phonetic pronunciation for verses',
    nextChapter: 'Next Chapter',
    backToBeginning: 'Back to Chapters',
  },
  bn: {
    quranChapters: 'কুরআন অধ্যায়',
    verses: 'আয়াত',
    settings: 'সেটিংস',
    translationLanguage: 'অনুবাদ ভাষা',
    readingFontSize: 'ফন্ট সাইজ',
    fontSizeDesc: 'আরবি এবং অনুবাদ পাঠ্যের আকার পরিবর্তন করুন',
    preview: 'প্রিভিউ',
    appInformation: 'অ্যাপ তথ্য',
    version: 'ভার্সন',
    developer: 'ডেভেলপার',
    bismillahTranslation: 'পরম দয়ালু ও অসীম দয়াময় আল্লাহর নামে',
    showTransliteration: 'উচ্চারণ প্রদর্শন করুন',
    transliterationDesc: 'আয়াতের ধ্বনিগত উচ্চারণ প্রদর্শন করুন',
    nextChapter: 'পরবর্তী অধ্যায়',
    backToBeginning: 'অধ্যায়ে ফিরে যান',
  },
  id: {
    quranChapters: 'Daftar Surah',
    verses: 'Ayat',
    settings: 'Pengaturan',
    translationLanguage: 'Bahasa Terjemahan',
    readingFontSize: 'Ukuran Font',
    fontSizeDesc: 'Sesuaikan ukuran teks Arab dan terjemahan',
    preview: 'Pratinjau',
    appInformation: 'Informasi Aplikasi',
    version: 'Versi',
    developer: 'Pengembang',
    bismillahTranslation: 'Dengan nama Allah Yang Maha Pengasih, Maha Penyayang',
    showTransliteration: 'Tampilkan Transliterasi',
    transliterationDesc: 'Tampilkan pelafalan fonetik untuk ayat-ayat',
    nextChapter: 'Surah Berikutnya',
    backToBeginning: 'Kembali ke Daftar',
  },
  es: {
    quranChapters: 'Capítulos del Corán',
    verses: 'Versículos',
    settings: 'Ajustes',
    translationLanguage: 'Idioma de traducción',
    readingFontSize: 'Tamaño de fuente',
    fontSizeDesc: 'Ajustar el tamaño del texto árabe y de la traducción',
    preview: 'Previsualización',
    appInformation: 'Información de la aplicación',
    version: 'Versión',
    developer: 'Desarrollador',
    bismillahTranslation: 'En el nombre de Alá, el Compasivo, el Misericordioso',
    showTransliteration: 'Mostrar Transliteración',
    transliterationDesc: 'Mostrar la pronunciación fonética de los versículos',
    nextChapter: 'Siguiente Capítulo',
    backToBeginning: 'Volver a Capítulos',
  },
  fr: {
    quranChapters: 'Chapitres du Coran',
    verses: 'Versets',
    settings: 'Paramètres',
    translationLanguage: 'Langue de traduction',
    readingFontSize: 'Taille de police',
    fontSizeDesc: 'Ajuster la taille du texte arabe et de la traduction',
    preview: 'Aperçu',
    appInformation: 'Informations sur l\'application',
    version: 'Version',
    developer: 'Développeur',
    bismillahTranslation: 'Au nom d\'Allah, le Tout Miséricordieux, le Très Miséricordioso',
    showTransliteration: 'Afficher la translittération',
    transliterationDesc: 'Afficher la prononciation phonétique des versets',
    nextChapter: 'Chapitre Suivant',
    backToBeginning: 'Retour aux Chapitres',
  },
  ru: {
    quranChapters: 'Суры Корана',
    verses: 'Аяты',
    settings: 'Настройки',
    translationLanguage: 'Язык перевода',
    readingFontSize: 'Размер шрифта',
    fontSizeDesc: 'Настройте размер арабского текста и перевода',
    preview: 'Предпросмотр',
    appInformation: 'Информация о приложении',
    version: 'Версия',
    developer: 'Разработчик',
    bismillahTranslation: 'Во имя Аллаха, Милостивого, Милосердного',
    showTransliteration: 'Показать транслитерацию',
    transliterationDesc: 'Отображать фонетическое произношение аятов',
    nextChapter: 'Следующая Сура',
    backToBeginning: 'К Списку Групп',
  },
  sv: {
    quranChapters: 'Koranens kapitel',
    verses: 'Verser',
    settings: 'Inställningar',
    translationLanguage: 'Översättningsspråk',
    readingFontSize: 'Textstorlek',
    fontSizeDesc: 'Justera storleken på arabisk text och översättning',
    preview: 'Förhandsgranskning',
    appInformation: 'Appinformation',
    version: 'Version',
    developer: 'Utvecklare',
    bismillahTranslation: 'I Guds, den Nåderikes, den Barmhärtiges namn',
    showTransliteration: 'Visa translitterering',
    transliterationDesc: 'Visa fonetiskt uttal för verserna',
    nextChapter: 'Nästa Kapitel',
    backToBeginning: 'Tillbaka till Listan',
  },
  tr: {
    quranChapters: 'Kuran Sureleri',
    verses: 'Ayetler',
    settings: 'Ayarlar',
    translationLanguage: 'Çeviri Dili',
    readingFontSize: 'Yazı Tipi Boyutu',
    fontSizeDesc: 'Arapça ve çeviri metninin boyutunu ayarlayın',
    preview: 'Önizleme',
    appInformation: 'Uygulama Bilgisi',
    version: 'Sürüm',
    developer: 'Geliştirici',
    bismillahTranslation: 'Rahmân ve Rahîm olan Allah\'ın adıyla',
    showTransliteration: 'Transliterasyonu Göster',
    transliterationDesc: 'Ayetler için fonetik okunuşu göster',
    nextChapter: 'Sonraki Sure',
    backToBeginning: 'Listeye Geri Dön',
  },
  ur: {
    quranChapters: 'قرآن کی سورتیں',
    verses: 'آیات',
    settings: 'ترتیبات',
    translationLanguage: 'ترجمہ کی زبان',
    readingFontSize: 'فونٹ کا سائز',
    fontSizeDesc: 'عربی اور ترجمہ کے متن کا سائز درست کریں',
    preview: 'نمونہ',
    appInformation: 'ایپ کی معلومات',
    version: 'ورژن',
    developer: 'ڈویلپر',
    bismillahTranslation: 'اللہ کے نام سے شروع جو بڑا مہربان نہایت رحم والا ہے',
    showTransliteration: 'ترجمہ پکاریں',
    transliterationDesc: 'آیات کے لیے صوتی تلفظ دکھائیں',
    nextChapter: 'اگلی سورہ',
    backToBeginning: 'فہرست پر واپس',
  },
  zh: {
    quranChapters: '古兰经章节',
    verses: '节',
    settings: '设置',
    translationLanguage: '翻译语言',
    readingFontSize: '字体大小',
    fontSizeDesc: '调整阿拉伯语和翻译文本的大小',
    preview: '预览',
    appInformation: '应用信息',
    version: '版本',
    developer: '开发者',
    bismillahTranslation: '奉至仁至慈的真主之名',
    showTransliteration: '显示音译',
    transliterationDesc: '显示节的语音读法',
    nextChapter: '下一章',
    backToBeginning: '回到章节列表',
  },
};

export const getLocalizedString = (lang, key) => {
  const strings = LOCALIZED_STRINGS[lang] || LOCALIZED_STRINGS['en'];
  return strings[key] || LOCALIZED_STRINGS['en'][key];
};

const chapterMappings = {
  en: {
    1: require('../../assets/data/chapters/en/1.json'),
    2: require('../../assets/data/chapters/en/2.json'),
    3: require('../../assets/data/chapters/en/3.json'),
    4: require('../../assets/data/chapters/en/4.json'),
    5: require('../../assets/data/chapters/en/5.json'),
    6: require('../../assets/data/chapters/en/6.json'),
    7: require('../../assets/data/chapters/en/7.json'),
    8: require('../../assets/data/chapters/en/8.json'),
    9: require('../../assets/data/chapters/en/9.json'),
    10: require('../../assets/data/chapters/en/10.json'),
    11: require('../../assets/data/chapters/en/11.json'),
    12: require('../../assets/data/chapters/en/12.json'),
    13: require('../../assets/data/chapters/en/13.json'),
    14: require('../../assets/data/chapters/en/14.json'),
    15: require('../../assets/data/chapters/en/15.json'),
    16: require('../../assets/data/chapters/en/16.json'),
    17: require('../../assets/data/chapters/en/17.json'),
    18: require('../../assets/data/chapters/en/18.json'),
    19: require('../../assets/data/chapters/en/19.json'),
    20: require('../../assets/data/chapters/en/20.json'),
    21: require('../../assets/data/chapters/en/21.json'),
    22: require('../../assets/data/chapters/en/22.json'),
    23: require('../../assets/data/chapters/en/23.json'),
    24: require('../../assets/data/chapters/en/24.json'),
    25: require('../../assets/data/chapters/en/25.json'),
    26: require('../../assets/data/chapters/en/26.json'),
    27: require('../../assets/data/chapters/en/27.json'),
    28: require('../../assets/data/chapters/en/28.json'),
    29: require('../../assets/data/chapters/en/29.json'),
    30: require('../../assets/data/chapters/en/30.json'),
    31: require('../../assets/data/chapters/en/31.json'),
    32: require('../../assets/data/chapters/en/32.json'),
    33: require('../../assets/data/chapters/en/33.json'),
    34: require('../../assets/data/chapters/en/34.json'),
    35: require('../../assets/data/chapters/en/35.json'),
    36: require('../../assets/data/chapters/en/36.json'),
    37: require('../../assets/data/chapters/en/37.json'),
    38: require('../../assets/data/chapters/en/38.json'),
    39: require('../../assets/data/chapters/en/39.json'),
    40: require('../../assets/data/chapters/en/40.json'),
    41: require('../../assets/data/chapters/en/41.json'),
    42: require('../../assets/data/chapters/en/42.json'),
    43: require('../../assets/data/chapters/en/43.json'),
    44: require('../../assets/data/chapters/en/44.json'),
    45: require('../../assets/data/chapters/en/45.json'),
    46: require('../../assets/data/chapters/en/46.json'),
    47: require('../../assets/data/chapters/en/47.json'),
    48: require('../../assets/data/chapters/en/48.json'),
    49: require('../../assets/data/chapters/en/49.json'),
    50: require('../../assets/data/chapters/en/50.json'),
    51: require('../../assets/data/chapters/en/51.json'),
    52: require('../../assets/data/chapters/en/52.json'),
    53: require('../../assets/data/chapters/en/53.json'),
    54: require('../../assets/data/chapters/en/54.json'),
    55: require('../../assets/data/chapters/en/55.json'),
    56: require('../../assets/data/chapters/en/56.json'),
    57: require('../../assets/data/chapters/en/57.json'),
    58: require('../../assets/data/chapters/en/58.json'),
    59: require('../../assets/data/chapters/en/59.json'),
    60: require('../../assets/data/chapters/en/60.json'),
    61: require('../../assets/data/chapters/en/61.json'),
    62: require('../../assets/data/chapters/en/62.json'),
    63: require('../../assets/data/chapters/en/63.json'),
    64: require('../../assets/data/chapters/en/64.json'),
    65: require('../../assets/data/chapters/en/65.json'),
    66: require('../../assets/data/chapters/en/66.json'),
    67: require('../../assets/data/chapters/en/67.json'),
    68: require('../../assets/data/chapters/en/68.json'),
    69: require('../../assets/data/chapters/en/69.json'),
    70: require('../../assets/data/chapters/en/70.json'),
    71: require('../../assets/data/chapters/en/71.json'),
    72: require('../../assets/data/chapters/en/72.json'),
    73: require('../../assets/data/chapters/en/73.json'),
    74: require('../../assets/data/chapters/en/74.json'),
    75: require('../../assets/data/chapters/en/75.json'),
    76: require('../../assets/data/chapters/en/76.json'),
    77: require('../../assets/data/chapters/en/77.json'),
    78: require('../../assets/data/chapters/en/78.json'),
    79: require('../../assets/data/chapters/en/79.json'),
    80: require('../../assets/data/chapters/en/80.json'),
    81: require('../../assets/data/chapters/en/81.json'),
    82: require('../../assets/data/chapters/en/82.json'),
    83: require('../../assets/data/chapters/en/83.json'),
    84: require('../../assets/data/chapters/en/84.json'),
    85: require('../../assets/data/chapters/en/85.json'),
    86: require('../../assets/data/chapters/en/86.json'),
    87: require('../../assets/data/chapters/en/87.json'),
    88: require('../../assets/data/chapters/en/88.json'),
    89: require('../../assets/data/chapters/en/89.json'),
    90: require('../../assets/data/chapters/en/90.json'),
    91: require('../../assets/data/chapters/en/91.json'),
    92: require('../../assets/data/chapters/en/92.json'),
    93: require('../../assets/data/chapters/en/93.json'),
    94: require('../../assets/data/chapters/en/94.json'),
    95: require('../../assets/data/chapters/en/95.json'),
    96: require('../../assets/data/chapters/en/96.json'),
    97: require('../../assets/data/chapters/en/97.json'),
    98: require('../../assets/data/chapters/en/98.json'),
    99: require('../../assets/data/chapters/en/99.json'),
    100: require('../../assets/data/chapters/en/100.json'),
    101: require('../../assets/data/chapters/en/101.json'),
    102: require('../../assets/data/chapters/en/102.json'),
    103: require('../../assets/data/chapters/en/103.json'),
    104: require('../../assets/data/chapters/en/104.json'),
    105: require('../../assets/data/chapters/en/105.json'),
    106: require('../../assets/data/chapters/en/106.json'),
    107: require('../../assets/data/chapters/en/107.json'),
    108: require('../../assets/data/chapters/en/108.json'),
    109: require('../../assets/data/chapters/en/109.json'),
    110: require('../../assets/data/chapters/en/110.json'),
    111: require('../../assets/data/chapters/en/111.json'),
    112: require('../../assets/data/chapters/en/112.json'),
    113: require('../../assets/data/chapters/en/113.json'),
    114: require('../../assets/data/chapters/en/114.json'),
  },
  bn: {
    1: require('../../assets/data/chapters/bn/1.json'),
    2: require('../../assets/data/chapters/bn/2.json'),
    3: require('../../assets/data/chapters/bn/3.json'),
    4: require('../../assets/data/chapters/bn/4.json'),
    5: require('../../assets/data/chapters/bn/5.json'),
    6: require('../../assets/data/chapters/bn/6.json'),
    7: require('../../assets/data/chapters/bn/7.json'),
    8: require('../../assets/data/chapters/bn/8.json'),
    9: require('../../assets/data/chapters/bn/9.json'),
    10: require('../../assets/data/chapters/bn/10.json'),
    11: require('../../assets/data/chapters/bn/11.json'),
    12: require('../../assets/data/chapters/bn/12.json'),
    13: require('../../assets/data/chapters/bn/13.json'),
    14: require('../../assets/data/chapters/bn/14.json'),
    15: require('../../assets/data/chapters/bn/15.json'),
    16: require('../../assets/data/chapters/bn/16.json'),
    17: require('../../assets/data/chapters/bn/17.json'),
    18: require('../../assets/data/chapters/bn/18.json'),
    19: require('../../assets/data/chapters/bn/19.json'),
    20: require('../../assets/data/chapters/bn/20.json'),
    21: require('../../assets/data/chapters/bn/21.json'),
    22: require('../../assets/data/chapters/bn/22.json'),
    23: require('../../assets/data/chapters/bn/23.json'),
    24: require('../../assets/data/chapters/bn/24.json'),
    25: require('../../assets/data/chapters/bn/25.json'),
    26: require('../../assets/data/chapters/bn/26.json'),
    27: require('../../assets/data/chapters/bn/27.json'),
    28: require('../../assets/data/chapters/bn/28.json'),
    29: require('../../assets/data/chapters/bn/29.json'),
    30: require('../../assets/data/chapters/bn/30.json'),
    31: require('../../assets/data/chapters/bn/31.json'),
    32: require('../../assets/data/chapters/bn/32.json'),
    33: require('../../assets/data/chapters/bn/33.json'),
    34: require('../../assets/data/chapters/bn/34.json'),
    35: require('../../assets/data/chapters/bn/35.json'),
    36: require('../../assets/data/chapters/bn/36.json'),
    37: require('../../assets/data/chapters/bn/37.json'),
    38: require('../../assets/data/chapters/bn/38.json'),
    39: require('../../assets/data/chapters/bn/39.json'),
    40: require('../../assets/data/chapters/bn/40.json'),
    41: require('../../assets/data/chapters/bn/41.json'),
    42: require('../../assets/data/chapters/bn/42.json'),
    43: require('../../assets/data/chapters/bn/43.json'),
    44: require('../../assets/data/chapters/bn/44.json'),
    45: require('../../assets/data/chapters/bn/45.json'),
    46: require('../../assets/data/chapters/bn/46.json'),
    47: require('../../assets/data/chapters/bn/47.json'),
    48: require('../../assets/data/chapters/bn/48.json'),
    49: require('../../assets/data/chapters/bn/49.json'),
    50: require('../../assets/data/chapters/bn/50.json'),
    51: require('../../assets/data/chapters/bn/51.json'),
    52: require('../../assets/data/chapters/bn/52.json'),
    53: require('../../assets/data/chapters/bn/53.json'),
    54: require('../../assets/data/chapters/bn/54.json'),
    55: require('../../assets/data/chapters/bn/55.json'),
    56: require('../../assets/data/chapters/bn/56.json'),
    57: require('../../assets/data/chapters/bn/57.json'),
    58: require('../../assets/data/chapters/bn/58.json'),
    59: require('../../assets/data/chapters/bn/59.json'),
    60: require('../../assets/data/chapters/bn/60.json'),
    61: require('../../assets/data/chapters/bn/61.json'),
    62: require('../../assets/data/chapters/bn/62.json'),
    63: require('../../assets/data/chapters/bn/63.json'),
    64: require('../../assets/data/chapters/bn/64.json'),
    65: require('../../assets/data/chapters/bn/65.json'),
    66: require('../../assets/data/chapters/bn/66.json'),
    67: require('../../assets/data/chapters/bn/67.json'),
    68: require('../../assets/data/chapters/bn/68.json'),
    69: require('../../assets/data/chapters/bn/69.json'),
    70: require('../../assets/data/chapters/bn/70.json'),
    71: require('../../assets/data/chapters/bn/71.json'),
    72: require('../../assets/data/chapters/bn/72.json'),
    73: require('../../assets/data/chapters/bn/73.json'),
    74: require('../../assets/data/chapters/bn/74.json'),
    75: require('../../assets/data/chapters/bn/75.json'),
    76: require('../../assets/data/chapters/bn/76.json'),
    77: require('../../assets/data/chapters/bn/77.json'),
    78: require('../../assets/data/chapters/bn/78.json'),
    79: require('../../assets/data/chapters/bn/79.json'),
    80: require('../../assets/data/chapters/bn/80.json'),
    81: require('../../assets/data/chapters/bn/81.json'),
    82: require('../../assets/data/chapters/bn/82.json'),
    83: require('../../assets/data/chapters/bn/83.json'),
    84: require('../../assets/data/chapters/bn/84.json'),
    85: require('../../assets/data/chapters/bn/85.json'),
    86: require('../../assets/data/chapters/bn/86.json'),
    87: require('../../assets/data/chapters/bn/87.json'),
    88: require('../../assets/data/chapters/bn/88.json'),
    89: require('../../assets/data/chapters/bn/89.json'),
    90: require('../../assets/data/chapters/bn/90.json'),
    91: require('../../assets/data/chapters/bn/91.json'),
    92: require('../../assets/data/chapters/bn/92.json'),
    93: require('../../assets/data/chapters/bn/93.json'),
    94: require('../../assets/data/chapters/bn/94.json'),
    95: require('../../assets/data/chapters/bn/95.json'),
    96: require('../../assets/data/chapters/bn/96.json'),
    97: require('../../assets/data/chapters/bn/97.json'),
    98: require('../../assets/data/chapters/bn/98.json'),
    99: require('../../assets/data/chapters/bn/99.json'),
    100: require('../../assets/data/chapters/bn/100.json'),
    101: require('../../assets/data/chapters/bn/101.json'),
    102: require('../../assets/data/chapters/bn/102.json'),
    103: require('../../assets/data/chapters/bn/103.json'),
    104: require('../../assets/data/chapters/bn/104.json'),
    105: require('../../assets/data/chapters/bn/105.json'),
    106: require('../../assets/data/chapters/bn/106.json'),
    107: require('../../assets/data/chapters/bn/107.json'),
    108: require('../../assets/data/chapters/bn/108.json'),
    109: require('../../assets/data/chapters/bn/109.json'),
    110: require('../../assets/data/chapters/bn/110.json'),
    111: require('../../assets/data/chapters/bn/111.json'),
    112: require('../../assets/data/chapters/bn/112.json'),
    113: require('../../assets/data/chapters/bn/113.json'),
    114: require('../../assets/data/chapters/bn/114.json'),
  },
  es: {
    1: require('../../assets/data/chapters/es/1.json'),
    2: require('../../assets/data/chapters/es/2.json'),
    3: require('../../assets/data/chapters/es/3.json'),
    4: require('../../assets/data/chapters/es/4.json'),
    5: require('../../assets/data/chapters/es/5.json'),
    6: require('../../assets/data/chapters/es/6.json'),
    7: require('../../assets/data/chapters/es/7.json'),
    8: require('../../assets/data/chapters/es/8.json'),
    9: require('../../assets/data/chapters/es/9.json'),
    10: require('../../assets/data/chapters/es/10.json'),
    11: require('../../assets/data/chapters/es/11.json'),
    12: require('../../assets/data/chapters/es/12.json'),
    13: require('../../assets/data/chapters/es/13.json'),
    14: require('../../assets/data/chapters/es/14.json'),
    15: require('../../assets/data/chapters/es/15.json'),
    16: require('../../assets/data/chapters/es/16.json'),
    17: require('../../assets/data/chapters/es/17.json'),
    18: require('../../assets/data/chapters/es/18.json'),
    19: require('../../assets/data/chapters/es/19.json'),
    20: require('../../assets/data/chapters/es/20.json'),
    21: require('../../assets/data/chapters/es/21.json'),
    22: require('../../assets/data/chapters/es/22.json'),
    23: require('../../assets/data/chapters/es/23.json'),
    24: require('../../assets/data/chapters/es/24.json'),
    25: require('../../assets/data/chapters/es/25.json'),
    26: require('../../assets/data/chapters/es/26.json'),
    27: require('../../assets/data/chapters/es/27.json'),
    28: require('../../assets/data/chapters/es/28.json'),
    29: require('../../assets/data/chapters/es/29.json'),
    30: require('../../assets/data/chapters/es/30.json'),
    31: require('../../assets/data/chapters/es/31.json'),
    32: require('../../assets/data/chapters/es/32.json'),
    33: require('../../assets/data/chapters/es/33.json'),
    34: require('../../assets/data/chapters/es/34.json'),
    35: require('../../assets/data/chapters/es/35.json'),
    36: require('../../assets/data/chapters/es/36.json'),
    37: require('../../assets/data/chapters/es/37.json'),
    38: require('../../assets/data/chapters/es/38.json'),
    39: require('../../assets/data/chapters/es/39.json'),
    40: require('../../assets/data/chapters/es/40.json'),
    41: require('../../assets/data/chapters/es/41.json'),
    42: require('../../assets/data/chapters/es/42.json'),
    43: require('../../assets/data/chapters/es/43.json'),
    44: require('../../assets/data/chapters/es/44.json'),
    45: require('../../assets/data/chapters/es/45.json'),
    46: require('../../assets/data/chapters/es/46.json'),
    47: require('../../assets/data/chapters/es/47.json'),
    48: require('../../assets/data/chapters/es/48.json'),
    49: require('../../assets/data/chapters/es/49.json'),
    50: require('../../assets/data/chapters/es/50.json'),
    51: require('../../assets/data/chapters/es/51.json'),
    52: require('../../assets/data/chapters/es/52.json'),
    53: require('../../assets/data/chapters/es/53.json'),
    54: require('../../assets/data/chapters/es/54.json'),
    55: require('../../assets/data/chapters/es/55.json'),
    56: require('../../assets/data/chapters/es/56.json'),
    57: require('../../assets/data/chapters/es/57.json'),
    58: require('../../assets/data/chapters/es/58.json'),
    59: require('../../assets/data/chapters/es/59.json'),
    60: require('../../assets/data/chapters/es/60.json'),
    61: require('../../assets/data/chapters/es/61.json'),
    62: require('../../assets/data/chapters/es/62.json'),
    63: require('../../assets/data/chapters/es/63.json'),
    64: require('../../assets/data/chapters/es/64.json'),
    65: require('../../assets/data/chapters/es/65.json'),
    66: require('../../assets/data/chapters/es/66.json'),
    67: require('../../assets/data/chapters/es/67.json'),
    68: require('../../assets/data/chapters/es/68.json'),
    69: require('../../assets/data/chapters/es/69.json'),
    70: require('../../assets/data/chapters/es/70.json'),
    71: require('../../assets/data/chapters/es/71.json'),
    72: require('../../assets/data/chapters/es/72.json'),
    73: require('../../assets/data/chapters/es/73.json'),
    74: require('../../assets/data/chapters/es/74.json'),
    75: require('../../assets/data/chapters/es/75.json'),
    76: require('../../assets/data/chapters/es/76.json'),
    77: require('../../assets/data/chapters/es/77.json'),
    78: require('../../assets/data/chapters/es/78.json'),
    79: require('../../assets/data/chapters/es/79.json'),
    80: require('../../assets/data/chapters/es/80.json'),
    81: require('../../assets/data/chapters/es/81.json'),
    82: require('../../assets/data/chapters/es/82.json'),
    83: require('../../assets/data/chapters/es/83.json'),
    84: require('../../assets/data/chapters/es/84.json'),
    85: require('../../assets/data/chapters/es/85.json'),
    86: require('../../assets/data/chapters/es/86.json'),
    87: require('../../assets/data/chapters/es/87.json'),
    88: require('../../assets/data/chapters/es/88.json'),
    89: require('../../assets/data/chapters/es/89.json'),
    90: require('../../assets/data/chapters/es/90.json'),
    91: require('../../assets/data/chapters/es/91.json'),
    92: require('../../assets/data/chapters/es/92.json'),
    93: require('../../assets/data/chapters/es/93.json'),
    94: require('../../assets/data/chapters/es/94.json'),
    95: require('../../assets/data/chapters/es/95.json'),
    96: require('../../assets/data/chapters/es/96.json'),
    97: require('../../assets/data/chapters/es/97.json'),
    98: require('../../assets/data/chapters/es/98.json'),
    99: require('../../assets/data/chapters/es/99.json'),
    100: require('../../assets/data/chapters/es/100.json'),
    101: require('../../assets/data/chapters/es/101.json'),
    102: require('../../assets/data/chapters/es/102.json'),
    103: require('../../assets/data/chapters/es/103.json'),
    104: require('../../assets/data/chapters/es/104.json'),
    105: require('../../assets/data/chapters/es/105.json'),
    106: require('../../assets/data/chapters/es/106.json'),
    107: require('../../assets/data/chapters/es/107.json'),
    108: require('../../assets/data/chapters/es/108.json'),
    109: require('../../assets/data/chapters/es/109.json'),
    110: require('../../assets/data/chapters/es/110.json'),
    111: require('../../assets/data/chapters/es/111.json'),
    112: require('../../assets/data/chapters/es/112.json'),
    113: require('../../assets/data/chapters/es/113.json'),
    114: require('../../assets/data/chapters/es/114.json'),
  },
  fr: {
    1: require('../../assets/data/chapters/fr/1.json'),
    2: require('../../assets/data/chapters/fr/2.json'),
    3: require('../../assets/data/chapters/fr/3.json'),
    4: require('../../assets/data/chapters/fr/4.json'),
    5: require('../../assets/data/chapters/fr/5.json'),
    6: require('../../assets/data/chapters/fr/6.json'),
    7: require('../../assets/data/chapters/fr/7.json'),
    8: require('../../assets/data/chapters/fr/8.json'),
    9: require('../../assets/data/chapters/fr/9.json'),
    10: require('../../assets/data/chapters/fr/10.json'),
    11: require('../../assets/data/chapters/fr/11.json'),
    12: require('../../assets/data/chapters/fr/12.json'),
    13: require('../../assets/data/chapters/fr/13.json'),
    14: require('../../assets/data/chapters/fr/14.json'),
    15: require('../../assets/data/chapters/fr/15.json'),
    16: require('../../assets/data/chapters/fr/16.json'),
    17: require('../../assets/data/chapters/fr/17.json'),
    18: require('../../assets/data/chapters/fr/18.json'),
    19: require('../../assets/data/chapters/fr/19.json'),
    20: require('../../assets/data/chapters/fr/20.json'),
    21: require('../../assets/data/chapters/fr/21.json'),
    22: require('../../assets/data/chapters/fr/22.json'),
    23: require('../../assets/data/chapters/fr/23.json'),
    24: require('../../assets/data/chapters/fr/24.json'),
    25: require('../../assets/data/chapters/fr/25.json'),
    26: require('../../assets/data/chapters/fr/26.json'),
    27: require('../../assets/data/chapters/fr/27.json'),
    28: require('../../assets/data/chapters/fr/28.json'),
    29: require('../../assets/data/chapters/fr/29.json'),
    30: require('../../assets/data/chapters/fr/30.json'),
    31: require('../../assets/data/chapters/fr/31.json'),
    32: require('../../assets/data/chapters/fr/32.json'),
    33: require('../../assets/data/chapters/fr/33.json'),
    34: require('../../assets/data/chapters/fr/34.json'),
    35: require('../../assets/data/chapters/fr/35.json'),
    36: require('../../assets/data/chapters/fr/36.json'),
    37: require('../../assets/data/chapters/fr/37.json'),
    38: require('../../assets/data/chapters/fr/38.json'),
    39: require('../../assets/data/chapters/fr/39.json'),
    40: require('../../assets/data/chapters/fr/40.json'),
    41: require('../../assets/data/chapters/fr/41.json'),
    42: require('../../assets/data/chapters/fr/42.json'),
    43: require('../../assets/data/chapters/fr/43.json'),
    44: require('../../assets/data/chapters/fr/44.json'),
    45: require('../../assets/data/chapters/fr/45.json'),
    46: require('../../assets/data/chapters/fr/46.json'),
    47: require('../../assets/data/chapters/fr/47.json'),
    48: require('../../assets/data/chapters/fr/48.json'),
    49: require('../../assets/data/chapters/fr/49.json'),
    50: require('../../assets/data/chapters/fr/50.json'),
    51: require('../../assets/data/chapters/fr/51.json'),
    52: require('../../assets/data/chapters/fr/52.json'),
    53: require('../../assets/data/chapters/fr/53.json'),
    54: require('../../assets/data/chapters/fr/54.json'),
    55: require('../../assets/data/chapters/fr/55.json'),
    56: require('../../assets/data/chapters/fr/56.json'),
    57: require('../../assets/data/chapters/fr/57.json'),
    58: require('../../assets/data/chapters/fr/58.json'),
    59: require('../../assets/data/chapters/fr/59.json'),
    60: require('../../assets/data/chapters/fr/60.json'),
    61: require('../../assets/data/chapters/fr/61.json'),
    62: require('../../assets/data/chapters/fr/62.json'),
    63: require('../../assets/data/chapters/fr/63.json'),
    64: require('../../assets/data/chapters/fr/64.json'),
    65: require('../../assets/data/chapters/fr/65.json'),
    66: require('../../assets/data/chapters/fr/66.json'),
    67: require('../../assets/data/chapters/fr/67.json'),
    68: require('../../assets/data/chapters/fr/68.json'),
    69: require('../../assets/data/chapters/fr/69.json'),
    70: require('../../assets/data/chapters/fr/70.json'),
    71: require('../../assets/data/chapters/fr/71.json'),
    72: require('../../assets/data/chapters/fr/72.json'),
    73: require('../../assets/data/chapters/fr/73.json'),
    74: require('../../assets/data/chapters/fr/74.json'),
    75: require('../../assets/data/chapters/fr/75.json'),
    76: require('../../assets/data/chapters/fr/76.json'),
    77: require('../../assets/data/chapters/fr/77.json'),
    78: require('../../assets/data/chapters/fr/78.json'),
    79: require('../../assets/data/chapters/fr/79.json'),
    80: require('../../assets/data/chapters/fr/80.json'),
    81: require('../../assets/data/chapters/fr/81.json'),
    82: require('../../assets/data/chapters/fr/82.json'),
    83: require('../../assets/data/chapters/fr/83.json'),
    84: require('../../assets/data/chapters/fr/84.json'),
    85: require('../../assets/data/chapters/fr/85.json'),
    86: require('../../assets/data/chapters/fr/86.json'),
    87: require('../../assets/data/chapters/fr/87.json'),
    88: require('../../assets/data/chapters/fr/88.json'),
    89: require('../../assets/data/chapters/fr/89.json'),
    90: require('../../assets/data/chapters/fr/90.json'),
    91: require('../../assets/data/chapters/fr/91.json'),
    92: require('../../assets/data/chapters/fr/92.json'),
    93: require('../../assets/data/chapters/fr/93.json'),
    94: require('../../assets/data/chapters/fr/94.json'),
    95: require('../../assets/data/chapters/fr/95.json'),
    96: require('../../assets/data/chapters/fr/96.json'),
    97: require('../../assets/data/chapters/fr/97.json'),
    98: require('../../assets/data/chapters/fr/98.json'),
    99: require('../../assets/data/chapters/fr/99.json'),
    100: require('../../assets/data/chapters/fr/100.json'),
    101: require('../../assets/data/chapters/fr/101.json'),
    102: require('../../assets/data/chapters/fr/102.json'),
    103: require('../../assets/data/chapters/fr/103.json'),
    104: require('../../assets/data/chapters/fr/104.json'),
    105: require('../../assets/data/chapters/fr/105.json'),
    106: require('../../assets/data/chapters/fr/106.json'),
    107: require('../../assets/data/chapters/fr/107.json'),
    108: require('../../assets/data/chapters/fr/108.json'),
    109: require('../../assets/data/chapters/fr/109.json'),
    110: require('../../assets/data/chapters/fr/110.json'),
    111: require('../../assets/data/chapters/fr/111.json'),
    112: require('../../assets/data/chapters/fr/112.json'),
    113: require('../../assets/data/chapters/fr/113.json'),
    114: require('../../assets/data/chapters/fr/114.json'),
  },
  id: {
    1: require('../../assets/data/chapters/id/1.json'),
    2: require('../../assets/data/chapters/id/2.json'),
    3: require('../../assets/data/chapters/id/3.json'),
    4: require('../../assets/data/chapters/id/4.json'),
    5: require('../../assets/data/chapters/id/5.json'),
    6: require('../../assets/data/chapters/id/6.json'),
    7: require('../../assets/data/chapters/id/7.json'),
    8: require('../../assets/data/chapters/id/8.json'),
    9: require('../../assets/data/chapters/id/9.json'),
    10: require('../../assets/data/chapters/id/10.json'),
    11: require('../../assets/data/chapters/id/11.json'),
    12: require('../../assets/data/chapters/id/12.json'),
    13: require('../../assets/data/chapters/id/13.json'),
    14: require('../../assets/data/chapters/id/14.json'),
    15: require('../../assets/data/chapters/id/15.json'),
    16: require('../../assets/data/chapters/id/16.json'),
    17: require('../../assets/data/chapters/id/17.json'),
    18: require('../../assets/data/chapters/id/18.json'),
    19: require('../../assets/data/chapters/id/19.json'),
    20: require('../../assets/data/chapters/id/20.json'),
    21: require('../../assets/data/chapters/id/21.json'),
    22: require('../../assets/data/chapters/id/22.json'),
    23: require('../../assets/data/chapters/id/23.json'),
    24: require('../../assets/data/chapters/id/24.json'),
    25: require('../../assets/data/chapters/id/25.json'),
    26: require('../../assets/data/chapters/id/26.json'),
    27: require('../../assets/data/chapters/id/27.json'),
    28: require('../../assets/data/chapters/id/28.json'),
    29: require('../../assets/data/chapters/id/29.json'),
    30: require('../../assets/data/chapters/id/30.json'),
    31: require('../../assets/data/chapters/id/31.json'),
    32: require('../../assets/data/chapters/id/32.json'),
    33: require('../../assets/data/chapters/id/33.json'),
    34: require('../../assets/data/chapters/id/34.json'),
    35: require('../../assets/data/chapters/id/35.json'),
    36: require('../../assets/data/chapters/id/36.json'),
    37: require('../../assets/data/chapters/id/37.json'),
    38: require('../../assets/data/chapters/id/38.json'),
    39: require('../../assets/data/chapters/id/39.json'),
    40: require('../../assets/data/chapters/id/40.json'),
    41: require('../../assets/data/chapters/id/41.json'),
    42: require('../../assets/data/chapters/id/42.json'),
    43: require('../../assets/data/chapters/id/43.json'),
    44: require('../../assets/data/chapters/id/44.json'),
    45: require('../../assets/data/chapters/id/45.json'),
    46: require('../../assets/data/chapters/id/46.json'),
    47: require('../../assets/data/chapters/id/47.json'),
    48: require('../../assets/data/chapters/id/48.json'),
    49: require('../../assets/data/chapters/id/49.json'),
    50: require('../../assets/data/chapters/id/50.json'),
    51: require('../../assets/data/chapters/id/51.json'),
    52: require('../../assets/data/chapters/id/52.json'),
    53: require('../../assets/data/chapters/id/53.json'),
    54: require('../../assets/data/chapters/id/54.json'),
    55: require('../../assets/data/chapters/id/55.json'),
    56: require('../../assets/data/chapters/id/56.json'),
    57: require('../../assets/data/chapters/id/57.json'),
    58: require('../../assets/data/chapters/id/58.json'),
    59: require('../../assets/data/chapters/id/59.json'),
    60: require('../../assets/data/chapters/id/60.json'),
    61: require('../../assets/data/chapters/id/61.json'),
    62: require('../../assets/data/chapters/id/62.json'),
    63: require('../../assets/data/chapters/id/63.json'),
    64: require('../../assets/data/chapters/id/64.json'),
    65: require('../../assets/data/chapters/id/65.json'),
    66: require('../../assets/data/chapters/id/66.json'),
    67: require('../../assets/data/chapters/id/67.json'),
    68: require('../../assets/data/chapters/id/68.json'),
    69: require('../../assets/data/chapters/id/69.json'),
    70: require('../../assets/data/chapters/id/70.json'),
    71: require('../../assets/data/chapters/id/71.json'),
    72: require('../../assets/data/chapters/id/72.json'),
    73: require('../../assets/data/chapters/id/73.json'),
    74: require('../../assets/data/chapters/id/74.json'),
    75: require('../../assets/data/chapters/id/75.json'),
    76: require('../../assets/data/chapters/id/76.json'),
    77: require('../../assets/data/chapters/id/77.json'),
    78: require('../../assets/data/chapters/id/78.json'),
    79: require('../../assets/data/chapters/id/79.json'),
    80: require('../../assets/data/chapters/id/80.json'),
    81: require('../../assets/data/chapters/id/81.json'),
    82: require('../../assets/data/chapters/id/82.json'),
    83: require('../../assets/data/chapters/id/83.json'),
    84: require('../../assets/data/chapters/id/84.json'),
    85: require('../../assets/data/chapters/id/85.json'),
    86: require('../../assets/data/chapters/id/86.json'),
    87: require('../../assets/data/chapters/id/87.json'),
    88: require('../../assets/data/chapters/id/88.json'),
    89: require('../../assets/data/chapters/id/89.json'),
    90: require('../../assets/data/chapters/id/90.json'),
    91: require('../../assets/data/chapters/id/91.json'),
    92: require('../../assets/data/chapters/id/92.json'),
    93: require('../../assets/data/chapters/id/93.json'),
    94: require('../../assets/data/chapters/id/94.json'),
    95: require('../../assets/data/chapters/id/95.json'),
    96: require('../../assets/data/chapters/id/96.json'),
    97: require('../../assets/data/chapters/id/97.json'),
    98: require('../../assets/data/chapters/id/98.json'),
    99: require('../../assets/data/chapters/id/99.json'),
    100: require('../../assets/data/chapters/id/100.json'),
    101: require('../../assets/data/chapters/id/101.json'),
    102: require('../../assets/data/chapters/id/102.json'),
    103: require('../../assets/data/chapters/id/103.json'),
    104: require('../../assets/data/chapters/id/104.json'),
    105: require('../../assets/data/chapters/id/105.json'),
    106: require('../../assets/data/chapters/id/106.json'),
    107: require('../../assets/data/chapters/id/107.json'),
    108: require('../../assets/data/chapters/id/108.json'),
    109: require('../../assets/data/chapters/id/109.json'),
    110: require('../../assets/data/chapters/id/110.json'),
    111: require('../../assets/data/chapters/id/111.json'),
    112: require('../../assets/data/chapters/id/112.json'),
    113: require('../../assets/data/chapters/id/113.json'),
    114: require('../../assets/data/chapters/id/114.json'),
  },
  ru: {
    1: require('../../assets/data/chapters/ru/1.json'),
    2: require('../../assets/data/chapters/ru/2.json'),
    3: require('../../assets/data/chapters/ru/3.json'),
    4: require('../../assets/data/chapters/ru/4.json'),
    5: require('../../assets/data/chapters/ru/5.json'),
    6: require('../../assets/data/chapters/ru/6.json'),
    7: require('../../assets/data/chapters/ru/7.json'),
    8: require('../../assets/data/chapters/ru/8.json'),
    9: require('../../assets/data/chapters/ru/9.json'),
    10: require('../../assets/data/chapters/ru/10.json'),
    11: require('../../assets/data/chapters/ru/11.json'),
    12: require('../../assets/data/chapters/ru/12.json'),
    13: require('../../assets/data/chapters/ru/13.json'),
    14: require('../../assets/data/chapters/ru/14.json'),
    15: require('../../assets/data/chapters/ru/15.json'),
    16: require('../../assets/data/chapters/ru/16.json'),
    17: require('../../assets/data/chapters/ru/17.json'),
    18: require('../../assets/data/chapters/ru/18.json'),
    19: require('../../assets/data/chapters/ru/19.json'),
    20: require('../../assets/data/chapters/ru/20.json'),
    21: require('../../assets/data/chapters/ru/21.json'),
    22: require('../../assets/data/chapters/ru/22.json'),
    23: require('../../assets/data/chapters/ru/23.json'),
    24: require('../../assets/data/chapters/ru/24.json'),
    25: require('../../assets/data/chapters/ru/25.json'),
    26: require('../../assets/data/chapters/ru/26.json'),
    27: require('../../assets/data/chapters/ru/27.json'),
    28: require('../../assets/data/chapters/ru/28.json'),
    29: require('../../assets/data/chapters/ru/29.json'),
    30: require('../../assets/data/chapters/ru/30.json'),
    31: require('../../assets/data/chapters/ru/31.json'),
    32: require('../../assets/data/chapters/ru/32.json'),
    33: require('../../assets/data/chapters/ru/33.json'),
    34: require('../../assets/data/chapters/ru/34.json'),
    35: require('../../assets/data/chapters/ru/35.json'),
    36: require('../../assets/data/chapters/ru/36.json'),
    37: require('../../assets/data/chapters/ru/37.json'),
    38: require('../../assets/data/chapters/ru/38.json'),
    39: require('../../assets/data/chapters/ru/39.json'),
    40: require('../../assets/data/chapters/ru/40.json'),
    41: require('../../assets/data/chapters/ru/41.json'),
    42: require('../../assets/data/chapters/ru/42.json'),
    43: require('../../assets/data/chapters/ru/43.json'),
    44: require('../../assets/data/chapters/ru/44.json'),
    45: require('../../assets/data/chapters/ru/45.json'),
    46: require('../../assets/data/chapters/ru/46.json'),
    47: require('../../assets/data/chapters/ru/47.json'),
    48: require('../../assets/data/chapters/ru/48.json'),
    49: require('../../assets/data/chapters/ru/49.json'),
    50: require('../../assets/data/chapters/ru/50.json'),
    51: require('../../assets/data/chapters/ru/51.json'),
    52: require('../../assets/data/chapters/ru/52.json'),
    53: require('../../assets/data/chapters/ru/53.json'),
    54: require('../../assets/data/chapters/ru/54.json'),
    55: require('../../assets/data/chapters/ru/55.json'),
    56: require('../../assets/data/chapters/ru/56.json'),
    57: require('../../assets/data/chapters/ru/57.json'),
    58: require('../../assets/data/chapters/ru/58.json'),
    59: require('../../assets/data/chapters/ru/59.json'),
    60: require('../../assets/data/chapters/ru/60.json'),
    61: require('../../assets/data/chapters/ru/61.json'),
    62: require('../../assets/data/chapters/ru/62.json'),
    63: require('../../assets/data/chapters/ru/63.json'),
    64: require('../../assets/data/chapters/ru/64.json'),
    65: require('../../assets/data/chapters/ru/65.json'),
    66: require('../../assets/data/chapters/ru/66.json'),
    67: require('../../assets/data/chapters/ru/67.json'),
    68: require('../../assets/data/chapters/ru/68.json'),
    69: require('../../assets/data/chapters/ru/69.json'),
    70: require('../../assets/data/chapters/ru/70.json'),
    71: require('../../assets/data/chapters/ru/71.json'),
    72: require('../../assets/data/chapters/ru/72.json'),
    73: require('../../assets/data/chapters/ru/73.json'),
    74: require('../../assets/data/chapters/ru/74.json'),
    75: require('../../assets/data/chapters/ru/75.json'),
    76: require('../../assets/data/chapters/ru/76.json'),
    77: require('../../assets/data/chapters/ru/77.json'),
    78: require('../../assets/data/chapters/ru/78.json'),
    79: require('../../assets/data/chapters/ru/79.json'),
    80: require('../../assets/data/chapters/ru/80.json'),
    81: require('../../assets/data/chapters/ru/81.json'),
    82: require('../../assets/data/chapters/ru/82.json'),
    83: require('../../assets/data/chapters/ru/83.json'),
    84: require('../../assets/data/chapters/ru/84.json'),
    85: require('../../assets/data/chapters/ru/85.json'),
    86: require('../../assets/data/chapters/ru/86.json'),
    87: require('../../assets/data/chapters/ru/87.json'),
    88: require('../../assets/data/chapters/ru/88.json'),
    89: require('../../assets/data/chapters/ru/89.json'),
    90: require('../../assets/data/chapters/ru/90.json'),
    91: require('../../assets/data/chapters/ru/91.json'),
    92: require('../../assets/data/chapters/ru/92.json'),
    93: require('../../assets/data/chapters/ru/93.json'),
    94: require('../../assets/data/chapters/ru/94.json'),
    95: require('../../assets/data/chapters/ru/95.json'),
    96: require('../../assets/data/chapters/ru/96.json'),
    97: require('../../assets/data/chapters/ru/97.json'),
    98: require('../../assets/data/chapters/ru/98.json'),
    99: require('../../assets/data/chapters/ru/99.json'),
    100: require('../../assets/data/chapters/ru/100.json'),
    101: require('../../assets/data/chapters/ru/101.json'),
    102: require('../../assets/data/chapters/ru/102.json'),
    103: require('../../assets/data/chapters/ru/103.json'),
    104: require('../../assets/data/chapters/ru/104.json'),
    105: require('../../assets/data/chapters/ru/105.json'),
    106: require('../../assets/data/chapters/ru/106.json'),
    107: require('../../assets/data/chapters/ru/107.json'),
    108: require('../../assets/data/chapters/ru/108.json'),
    109: require('../../assets/data/chapters/ru/109.json'),
    110: require('../../assets/data/chapters/ru/110.json'),
    111: require('../../assets/data/chapters/ru/111.json'),
    112: require('../../assets/data/chapters/ru/112.json'),
    113: require('../../assets/data/chapters/ru/113.json'),
    114: require('../../assets/data/chapters/ru/114.json'),
  },
  sv: {
    1: require('../../assets/data/chapters/sv/1.json'),
    2: require('../../assets/data/chapters/sv/2.json'),
    3: require('../../assets/data/chapters/sv/3.json'),
    4: require('../../assets/data/chapters/sv/4.json'),
    5: require('../../assets/data/chapters/sv/5.json'),
    6: require('../../assets/data/chapters/sv/6.json'),
    7: require('../../assets/data/chapters/sv/7.json'),
    8: require('../../assets/data/chapters/sv/8.json'),
    9: require('../../assets/data/chapters/sv/9.json'),
    10: require('../../assets/data/chapters/sv/10.json'),
    11: require('../../assets/data/chapters/sv/11.json'),
    12: require('../../assets/data/chapters/sv/12.json'),
    13: require('../../assets/data/chapters/sv/13.json'),
    14: require('../../assets/data/chapters/sv/14.json'),
    15: require('../../assets/data/chapters/sv/15.json'),
    16: require('../../assets/data/chapters/sv/16.json'),
    17: require('../../assets/data/chapters/sv/17.json'),
    18: require('../../assets/data/chapters/sv/18.json'),
    19: require('../../assets/data/chapters/sv/19.json'),
    20: require('../../assets/data/chapters/sv/20.json'),
    21: require('../../assets/data/chapters/sv/21.json'),
    22: require('../../assets/data/chapters/sv/22.json'),
    23: require('../../assets/data/chapters/sv/23.json'),
    24: require('../../assets/data/chapters/sv/24.json'),
    25: require('../../assets/data/chapters/sv/25.json'),
    26: require('../../assets/data/chapters/sv/26.json'),
    27: require('../../assets/data/chapters/sv/27.json'),
    28: require('../../assets/data/chapters/sv/28.json'),
    29: require('../../assets/data/chapters/sv/29.json'),
    30: require('../../assets/data/chapters/sv/30.json'),
    31: require('../../assets/data/chapters/sv/31.json'),
    32: require('../../assets/data/chapters/sv/32.json'),
    33: require('../../assets/data/chapters/sv/33.json'),
    34: require('../../assets/data/chapters/sv/34.json'),
    35: require('../../assets/data/chapters/sv/35.json'),
    36: require('../../assets/data/chapters/sv/36.json'),
    37: require('../../assets/data/chapters/sv/37.json'),
    38: require('../../assets/data/chapters/sv/38.json'),
    39: require('../../assets/data/chapters/sv/39.json'),
    40: require('../../assets/data/chapters/sv/40.json'),
    41: require('../../assets/data/chapters/sv/41.json'),
    42: require('../../assets/data/chapters/sv/42.json'),
    43: require('../../assets/data/chapters/sv/43.json'),
    44: require('../../assets/data/chapters/sv/44.json'),
    45: require('../../assets/data/chapters/sv/45.json'),
    46: require('../../assets/data/chapters/sv/46.json'),
    47: require('../../assets/data/chapters/sv/47.json'),
    48: require('../../assets/data/chapters/sv/48.json'),
    49: require('../../assets/data/chapters/sv/49.json'),
    50: require('../../assets/data/chapters/sv/50.json'),
    51: require('../../assets/data/chapters/sv/51.json'),
    52: require('../../assets/data/chapters/sv/52.json'),
    53: require('../../assets/data/chapters/sv/53.json'),
    54: require('../../assets/data/chapters/sv/54.json'),
    55: require('../../assets/data/chapters/sv/55.json'),
    56: require('../../assets/data/chapters/sv/56.json'),
    57: require('../../assets/data/chapters/sv/57.json'),
    58: require('../../assets/data/chapters/sv/58.json'),
    59: require('../../assets/data/chapters/sv/59.json'),
    60: require('../../assets/data/chapters/sv/60.json'),
    61: require('../../assets/data/chapters/sv/61.json'),
    62: require('../../assets/data/chapters/sv/62.json'),
    63: require('../../assets/data/chapters/sv/63.json'),
    64: require('../../assets/data/chapters/sv/64.json'),
    65: require('../../assets/data/chapters/sv/65.json'),
    66: require('../../assets/data/chapters/sv/66.json'),
    67: require('../../assets/data/chapters/sv/67.json'),
    68: require('../../assets/data/chapters/sv/68.json'),
    69: require('../../assets/data/chapters/sv/69.json'),
    70: require('../../assets/data/chapters/sv/70.json'),
    71: require('../../assets/data/chapters/sv/71.json'),
    72: require('../../assets/data/chapters/sv/72.json'),
    73: require('../../assets/data/chapters/sv/73.json'),
    74: require('../../assets/data/chapters/sv/74.json'),
    75: require('../../assets/data/chapters/sv/75.json'),
    76: require('../../assets/data/chapters/sv/76.json'),
    77: require('../../assets/data/chapters/sv/77.json'),
    78: require('../../assets/data/chapters/sv/78.json'),
    79: require('../../assets/data/chapters/sv/79.json'),
    80: require('../../assets/data/chapters/sv/80.json'),
    81: require('../../assets/data/chapters/sv/81.json'),
    82: require('../../assets/data/chapters/sv/82.json'),
    83: require('../../assets/data/chapters/sv/83.json'),
    84: require('../../assets/data/chapters/sv/84.json'),
    85: require('../../assets/data/chapters/sv/85.json'),
    86: require('../../assets/data/chapters/sv/86.json'),
    87: require('../../assets/data/chapters/sv/87.json'),
    88: require('../../assets/data/chapters/sv/88.json'),
    89: require('../../assets/data/chapters/sv/89.json'),
    90: require('../../assets/data/chapters/sv/90.json'),
    91: require('../../assets/data/chapters/sv/91.json'),
    92: require('../../assets/data/chapters/sv/92.json'),
    93: require('../../assets/data/chapters/sv/93.json'),
    94: require('../../assets/data/chapters/sv/94.json'),
    95: require('../../assets/data/chapters/sv/95.json'),
    96: require('../../assets/data/chapters/sv/96.json'),
    97: require('../../assets/data/chapters/sv/97.json'),
    98: require('../../assets/data/chapters/sv/98.json'),
    99: require('../../assets/data/chapters/sv/99.json'),
    100: require('../../assets/data/chapters/sv/100.json'),
    101: require('../../assets/data/chapters/sv/101.json'),
    102: require('../../assets/data/chapters/sv/102.json'),
    103: require('../../assets/data/chapters/sv/103.json'),
    104: require('../../assets/data/chapters/sv/104.json'),
    105: require('../../assets/data/chapters/sv/105.json'),
    106: require('../../assets/data/chapters/sv/106.json'),
    107: require('../../assets/data/chapters/sv/107.json'),
    108: require('../../assets/data/chapters/sv/108.json'),
    109: require('../../assets/data/chapters/sv/109.json'),
    110: require('../../assets/data/chapters/sv/110.json'),
    111: require('../../assets/data/chapters/sv/111.json'),
    112: require('../../assets/data/chapters/sv/112.json'),
    113: require('../../assets/data/chapters/sv/113.json'),
    114: require('../../assets/data/chapters/sv/114.json'),
  },
  tr: {
    1: require('../../assets/data/chapters/tr/1.json'),
    2: require('../../assets/data/chapters/tr/2.json'),
    3: require('../../assets/data/chapters/tr/3.json'),
    4: require('../../assets/data/chapters/tr/4.json'),
    5: require('../../assets/data/chapters/tr/5.json'),
    6: require('../../assets/data/chapters/tr/6.json'),
    7: require('../../assets/data/chapters/tr/7.json'),
    8: require('../../assets/data/chapters/tr/8.json'),
    9: require('../../assets/data/chapters/tr/9.json'),
    10: require('../../assets/data/chapters/tr/10.json'),
    11: require('../../assets/data/chapters/tr/11.json'),
    12: require('../../assets/data/chapters/tr/12.json'),
    13: require('../../assets/data/chapters/tr/13.json'),
    14: require('../../assets/data/chapters/tr/14.json'),
    15: require('../../assets/data/chapters/tr/15.json'),
    16: require('../../assets/data/chapters/tr/16.json'),
    17: require('../../assets/data/chapters/tr/17.json'),
    18: require('../../assets/data/chapters/tr/18.json'),
    19: require('../../assets/data/chapters/tr/19.json'),
    20: require('../../assets/data/chapters/tr/20.json'),
    21: require('../../assets/data/chapters/tr/21.json'),
    22: require('../../assets/data/chapters/tr/22.json'),
    23: require('../../assets/data/chapters/tr/23.json'),
    24: require('../../assets/data/chapters/tr/24.json'),
    25: require('../../assets/data/chapters/tr/25.json'),
    26: require('../../assets/data/chapters/tr/26.json'),
    27: require('../../assets/data/chapters/tr/27.json'),
    28: require('../../assets/data/chapters/tr/28.json'),
    29: require('../../assets/data/chapters/tr/29.json'),
    30: require('../../assets/data/chapters/tr/30.json'),
    31: require('../../assets/data/chapters/tr/31.json'),
    32: require('../../assets/data/chapters/tr/32.json'),
    33: require('../../assets/data/chapters/tr/33.json'),
    34: require('../../assets/data/chapters/tr/34.json'),
    35: require('../../assets/data/chapters/tr/35.json'),
    36: require('../../assets/data/chapters/tr/36.json'),
    37: require('../../assets/data/chapters/tr/37.json'),
    38: require('../../assets/data/chapters/tr/38.json'),
    39: require('../../assets/data/chapters/tr/39.json'),
    40: require('../../assets/data/chapters/tr/40.json'),
    41: require('../../assets/data/chapters/tr/41.json'),
    42: require('../../assets/data/chapters/tr/42.json'),
    43: require('../../assets/data/chapters/tr/43.json'),
    44: require('../../assets/data/chapters/tr/44.json'),
    45: require('../../assets/data/chapters/tr/45.json'),
    46: require('../../assets/data/chapters/tr/46.json'),
    47: require('../../assets/data/chapters/tr/47.json'),
    48: require('../../assets/data/chapters/tr/48.json'),
    49: require('../../assets/data/chapters/tr/49.json'),
    50: require('../../assets/data/chapters/tr/50.json'),
    51: require('../../assets/data/chapters/tr/51.json'),
    52: require('../../assets/data/chapters/tr/52.json'),
    53: require('../../assets/data/chapters/tr/53.json'),
    54: require('../../assets/data/chapters/tr/54.json'),
    55: require('../../assets/data/chapters/tr/55.json'),
    56: require('../../assets/data/chapters/tr/56.json'),
    57: require('../../assets/data/chapters/tr/57.json'),
    58: require('../../assets/data/chapters/tr/58.json'),
    59: require('../../assets/data/chapters/tr/59.json'),
    60: require('../../assets/data/chapters/tr/60.json'),
    61: require('../../assets/data/chapters/tr/61.json'),
    62: require('../../assets/data/chapters/tr/62.json'),
    63: require('../../assets/data/chapters/tr/63.json'),
    64: require('../../assets/data/chapters/tr/64.json'),
    65: require('../../assets/data/chapters/tr/65.json'),
    66: require('../../assets/data/chapters/tr/66.json'),
    67: require('../../assets/data/chapters/tr/67.json'),
    68: require('../../assets/data/chapters/tr/68.json'),
    69: require('../../assets/data/chapters/tr/69.json'),
    70: require('../../assets/data/chapters/tr/70.json'),
    71: require('../../assets/data/chapters/tr/71.json'),
    72: require('../../assets/data/chapters/tr/72.json'),
    73: require('../../assets/data/chapters/tr/73.json'),
    74: require('../../assets/data/chapters/tr/74.json'),
    75: require('../../assets/data/chapters/tr/75.json'),
    76: require('../../assets/data/chapters/tr/76.json'),
    77: require('../../assets/data/chapters/tr/77.json'),
    78: require('../../assets/data/chapters/tr/78.json'),
    79: require('../../assets/data/chapters/tr/79.json'),
    80: require('../../assets/data/chapters/tr/80.json'),
    81: require('../../assets/data/chapters/tr/81.json'),
    82: require('../../assets/data/chapters/tr/82.json'),
    83: require('../../assets/data/chapters/tr/83.json'),
    84: require('../../assets/data/chapters/tr/84.json'),
    85: require('../../assets/data/chapters/tr/85.json'),
    86: require('../../assets/data/chapters/tr/86.json'),
    87: require('../../assets/data/chapters/tr/87.json'),
    88: require('../../assets/data/chapters/tr/88.json'),
    89: require('../../assets/data/chapters/tr/89.json'),
    90: require('../../assets/data/chapters/tr/90.json'),
    91: require('../../assets/data/chapters/tr/91.json'),
    92: require('../../assets/data/chapters/tr/92.json'),
    93: require('../../assets/data/chapters/tr/93.json'),
    94: require('../../assets/data/chapters/tr/94.json'),
    95: require('../../assets/data/chapters/tr/95.json'),
    96: require('../../assets/data/chapters/tr/96.json'),
    97: require('../../assets/data/chapters/tr/97.json'),
    98: require('../../assets/data/chapters/tr/98.json'),
    99: require('../../assets/data/chapters/tr/99.json'),
    100: require('../../assets/data/chapters/tr/100.json'),
    101: require('../../assets/data/chapters/tr/101.json'),
    102: require('../../assets/data/chapters/tr/102.json'),
    103: require('../../assets/data/chapters/tr/103.json'),
    104: require('../../assets/data/chapters/tr/104.json'),
    105: require('../../assets/data/chapters/tr/105.json'),
    106: require('../../assets/data/chapters/tr/106.json'),
    107: require('../../assets/data/chapters/tr/107.json'),
    108: require('../../assets/data/chapters/tr/108.json'),
    109: require('../../assets/data/chapters/tr/109.json'),
    110: require('../../assets/data/chapters/tr/110.json'),
    111: require('../../assets/data/chapters/tr/111.json'),
    112: require('../../assets/data/chapters/tr/112.json'),
    113: require('../../assets/data/chapters/tr/113.json'),
    114: require('../../assets/data/chapters/tr/114.json'),
  },
  ur: {
    1: require('../../assets/data/chapters/ur/1.json'),
    2: require('../../assets/data/chapters/ur/2.json'),
    3: require('../../assets/data/chapters/ur/3.json'),
    4: require('../../assets/data/chapters/ur/4.json'),
    5: require('../../assets/data/chapters/ur/5.json'),
    6: require('../../assets/data/chapters/ur/6.json'),
    7: require('../../assets/data/chapters/ur/7.json'),
    8: require('../../assets/data/chapters/ur/8.json'),
    9: require('../../assets/data/chapters/ur/9.json'),
    10: require('../../assets/data/chapters/ur/10.json'),
    11: require('../../assets/data/chapters/ur/11.json'),
    12: require('../../assets/data/chapters/ur/12.json'),
    13: require('../../assets/data/chapters/ur/13.json'),
    14: require('../../assets/data/chapters/ur/14.json'),
    15: require('../../assets/data/chapters/ur/15.json'),
    16: require('../../assets/data/chapters/ur/16.json'),
    17: require('../../assets/data/chapters/ur/17.json'),
    18: require('../../assets/data/chapters/ur/18.json'),
    19: require('../../assets/data/chapters/ur/19.json'),
    20: require('../../assets/data/chapters/ur/20.json'),
    21: require('../../assets/data/chapters/ur/21.json'),
    22: require('../../assets/data/chapters/ur/22.json'),
    23: require('../../assets/data/chapters/ur/23.json'),
    24: require('../../assets/data/chapters/ur/24.json'),
    25: require('../../assets/data/chapters/ur/25.json'),
    26: require('../../assets/data/chapters/ur/26.json'),
    27: require('../../assets/data/chapters/ur/27.json'),
    28: require('../../assets/data/chapters/ur/28.json'),
    29: require('../../assets/data/chapters/ur/29.json'),
    30: require('../../assets/data/chapters/ur/30.json'),
    31: require('../../assets/data/chapters/ur/31.json'),
    32: require('../../assets/data/chapters/ur/32.json'),
    33: require('../../assets/data/chapters/ur/33.json'),
    34: require('../../assets/data/chapters/ur/34.json'),
    35: require('../../assets/data/chapters/ur/35.json'),
    36: require('../../assets/data/chapters/ur/36.json'),
    37: require('../../assets/data/chapters/ur/37.json'),
    38: require('../../assets/data/chapters/ur/38.json'),
    39: require('../../assets/data/chapters/ur/39.json'),
    40: require('../../assets/data/chapters/ur/40.json'),
    41: require('../../assets/data/chapters/ur/41.json'),
    42: require('../../assets/data/chapters/ur/42.json'),
    43: require('../../assets/data/chapters/ur/43.json'),
    44: require('../../assets/data/chapters/ur/44.json'),
    45: require('../../assets/data/chapters/ur/45.json'),
    46: require('../../assets/data/chapters/ur/46.json'),
    47: require('../../assets/data/chapters/ur/47.json'),
    48: require('../../assets/data/chapters/ur/48.json'),
    49: require('../../assets/data/chapters/ur/49.json'),
    50: require('../../assets/data/chapters/ur/50.json'),
    51: require('../../assets/data/chapters/ur/51.json'),
    52: require('../../assets/data/chapters/ur/52.json'),
    53: require('../../assets/data/chapters/ur/53.json'),
    54: require('../../assets/data/chapters/ur/54.json'),
    55: require('../../assets/data/chapters/ur/55.json'),
    56: require('../../assets/data/chapters/ur/56.json'),
    57: require('../../assets/data/chapters/ur/57.json'),
    58: require('../../assets/data/chapters/ur/58.json'),
    59: require('../../assets/data/chapters/ur/59.json'),
    60: require('../../assets/data/chapters/ur/60.json'),
    61: require('../../assets/data/chapters/ur/61.json'),
    62: require('../../assets/data/chapters/ur/62.json'),
    63: require('../../assets/data/chapters/ur/63.json'),
    64: require('../../assets/data/chapters/ur/64.json'),
    65: require('../../assets/data/chapters/ur/65.json'),
    66: require('../../assets/data/chapters/ur/66.json'),
    67: require('../../assets/data/chapters/ur/67.json'),
    68: require('../../assets/data/chapters/ur/68.json'),
    69: require('../../assets/data/chapters/ur/69.json'),
    70: require('../../assets/data/chapters/ur/70.json'),
    71: require('../../assets/data/chapters/ur/71.json'),
    72: require('../../assets/data/chapters/ur/72.json'),
    73: require('../../assets/data/chapters/ur/73.json'),
    74: require('../../assets/data/chapters/ur/74.json'),
    75: require('../../assets/data/chapters/ur/75.json'),
    76: require('../../assets/data/chapters/ur/76.json'),
    77: require('../../assets/data/chapters/ur/77.json'),
    78: require('../../assets/data/chapters/ur/78.json'),
    79: require('../../assets/data/chapters/ur/79.json'),
    80: require('../../assets/data/chapters/ur/80.json'),
    81: require('../../assets/data/chapters/ur/81.json'),
    82: require('../../assets/data/chapters/ur/82.json'),
    83: require('../../assets/data/chapters/ur/83.json'),
    84: require('../../assets/data/chapters/ur/84.json'),
    85: require('../../assets/data/chapters/ur/85.json'),
    86: require('../../assets/data/chapters/ur/86.json'),
    87: require('../../assets/data/chapters/ur/87.json'),
    88: require('../../assets/data/chapters/ur/88.json'),
    89: require('../../assets/data/chapters/ur/89.json'),
    90: require('../../assets/data/chapters/ur/90.json'),
    91: require('../../assets/data/chapters/ur/91.json'),
    92: require('../../assets/data/chapters/ur/92.json'),
    93: require('../../assets/data/chapters/ur/93.json'),
    94: require('../../assets/data/chapters/ur/94.json'),
    95: require('../../assets/data/chapters/ur/95.json'),
    96: require('../../assets/data/chapters/ur/96.json'),
    97: require('../../assets/data/chapters/ur/97.json'),
    98: require('../../assets/data/chapters/ur/98.json'),
    99: require('../../assets/data/chapters/ur/99.json'),
    100: require('../../assets/data/chapters/ur/100.json'),
    101: require('../../assets/data/chapters/ur/101.json'),
    102: require('../../assets/data/chapters/ur/102.json'),
    103: require('../../assets/data/chapters/ur/103.json'),
    104: require('../../assets/data/chapters/ur/104.json'),
    105: require('../../assets/data/chapters/ur/105.json'),
    106: require('../../assets/data/chapters/ur/106.json'),
    107: require('../../assets/data/chapters/ur/107.json'),
    108: require('../../assets/data/chapters/ur/108.json'),
    109: require('../../assets/data/chapters/ur/109.json'),
    110: require('../../assets/data/chapters/ur/110.json'),
    111: require('../../assets/data/chapters/ur/111.json'),
    112: require('../../assets/data/chapters/ur/112.json'),
    113: require('../../assets/data/chapters/ur/113.json'),
    114: require('../../assets/data/chapters/ur/114.json'),
  },
  zh: {
    1: require('../../assets/data/chapters/zh/1.json'),
    2: require('../../assets/data/chapters/zh/2.json'),
    3: require('../../assets/data/chapters/zh/3.json'),
    4: require('../../assets/data/chapters/zh/4.json'),
    5: require('../../assets/data/chapters/zh/5.json'),
    6: require('../../assets/data/chapters/zh/6.json'),
    7: require('../../assets/data/chapters/zh/7.json'),
    8: require('../../assets/data/chapters/zh/8.json'),
    9: require('../../assets/data/chapters/zh/9.json'),
    10: require('../../assets/data/chapters/zh/10.json'),
    11: require('../../assets/data/chapters/zh/11.json'),
    12: require('../../assets/data/chapters/zh/12.json'),
    13: require('../../assets/data/chapters/zh/13.json'),
    14: require('../../assets/data/chapters/zh/14.json'),
    15: require('../../assets/data/chapters/zh/15.json'),
    16: require('../../assets/data/chapters/zh/16.json'),
    17: require('../../assets/data/chapters/zh/17.json'),
    18: require('../../assets/data/chapters/zh/18.json'),
    19: require('../../assets/data/chapters/zh/19.json'),
    20: require('../../assets/data/chapters/zh/20.json'),
    21: require('../../assets/data/chapters/zh/21.json'),
    22: require('../../assets/data/chapters/zh/22.json'),
    23: require('../../assets/data/chapters/zh/23.json'),
    24: require('../../assets/data/chapters/zh/24.json'),
    25: require('../../assets/data/chapters/zh/25.json'),
    26: require('../../assets/data/chapters/zh/26.json'),
    27: require('../../assets/data/chapters/zh/27.json'),
    28: require('../../assets/data/chapters/zh/28.json'),
    29: require('../../assets/data/chapters/zh/29.json'),
    30: require('../../assets/data/chapters/zh/30.json'),
    31: require('../../assets/data/chapters/zh/31.json'),
    32: require('../../assets/data/chapters/zh/32.json'),
    33: require('../../assets/data/chapters/zh/33.json'),
    34: require('../../assets/data/chapters/zh/34.json'),
    35: require('../../assets/data/chapters/zh/35.json'),
    36: require('../../assets/data/chapters/zh/36.json'),
    37: require('../../assets/data/chapters/zh/37.json'),
    38: require('../../assets/data/chapters/zh/38.json'),
    39: require('../../assets/data/chapters/zh/39.json'),
    40: require('../../assets/data/chapters/zh/40.json'),
    41: require('../../assets/data/chapters/zh/41.json'),
    42: require('../../assets/data/chapters/zh/42.json'),
    43: require('../../assets/data/chapters/zh/43.json'),
    44: require('../../assets/data/chapters/zh/44.json'),
    45: require('../../assets/data/chapters/zh/45.json'),
    46: require('../../assets/data/chapters/zh/46.json'),
    47: require('../../assets/data/chapters/zh/47.json'),
    48: require('../../assets/data/chapters/zh/48.json'),
    49: require('../../assets/data/chapters/zh/49.json'),
    50: require('../../assets/data/chapters/zh/50.json'),
    51: require('../../assets/data/chapters/zh/51.json'),
    52: require('../../assets/data/chapters/zh/52.json'),
    53: require('../../assets/data/chapters/zh/53.json'),
    54: require('../../assets/data/chapters/zh/54.json'),
    55: require('../../assets/data/chapters/zh/55.json'),
    56: require('../../assets/data/chapters/zh/56.json'),
    57: require('../../assets/data/chapters/zh/57.json'),
    58: require('../../assets/data/chapters/zh/58.json'),
    59: require('../../assets/data/chapters/zh/59.json'),
    60: require('../../assets/data/chapters/zh/60.json'),
    61: require('../../assets/data/chapters/zh/61.json'),
    62: require('../../assets/data/chapters/zh/62.json'),
    63: require('../../assets/data/chapters/zh/63.json'),
    64: require('../../assets/data/chapters/zh/64.json'),
    65: require('../../assets/data/chapters/zh/65.json'),
    66: require('../../assets/data/chapters/zh/66.json'),
    67: require('../../assets/data/chapters/zh/67.json'),
    68: require('../../assets/data/chapters/zh/68.json'),
    69: require('../../assets/data/chapters/zh/69.json'),
    70: require('../../assets/data/chapters/zh/70.json'),
    71: require('../../assets/data/chapters/zh/71.json'),
    72: require('../../assets/data/chapters/zh/72.json'),
    73: require('../../assets/data/chapters/zh/73.json'),
    74: require('../../assets/data/chapters/zh/74.json'),
    75: require('../../assets/data/chapters/zh/75.json'),
    76: require('../../assets/data/chapters/zh/76.json'),
    77: require('../../assets/data/chapters/zh/77.json'),
    78: require('../../assets/data/chapters/zh/78.json'),
    79: require('../../assets/data/chapters/zh/79.json'),
    80: require('../../assets/data/chapters/zh/80.json'),
    81: require('../../assets/data/chapters/zh/81.json'),
    82: require('../../assets/data/chapters/zh/82.json'),
    83: require('../../assets/data/chapters/zh/83.json'),
    84: require('../../assets/data/chapters/zh/84.json'),
    85: require('../../assets/data/chapters/zh/85.json'),
    86: require('../../assets/data/chapters/zh/86.json'),
    87: require('../../assets/data/chapters/zh/87.json'),
    88: require('../../assets/data/chapters/zh/88.json'),
    89: require('../../assets/data/chapters/zh/89.json'),
    90: require('../../assets/data/chapters/zh/90.json'),
    91: require('../../assets/data/chapters/zh/91.json'),
    92: require('../../assets/data/chapters/zh/92.json'),
    93: require('../../assets/data/chapters/zh/93.json'),
    94: require('../../assets/data/chapters/zh/94.json'),
    95: require('../../assets/data/chapters/zh/95.json'),
    96: require('../../assets/data/chapters/zh/96.json'),
    97: require('../../assets/data/chapters/zh/97.json'),
    98: require('../../assets/data/chapters/zh/98.json'),
    99: require('../../assets/data/chapters/zh/99.json'),
    100: require('../../assets/data/chapters/zh/100.json'),
    101: require('../../assets/data/chapters/zh/101.json'),
    102: require('../../assets/data/chapters/zh/102.json'),
    103: require('../../assets/data/chapters/zh/103.json'),
    104: require('../../assets/data/chapters/zh/104.json'),
    105: require('../../assets/data/chapters/zh/105.json'),
    106: require('../../assets/data/chapters/zh/106.json'),
    107: require('../../assets/data/chapters/zh/107.json'),
    108: require('../../assets/data/chapters/zh/108.json'),
    109: require('../../assets/data/chapters/zh/109.json'),
    110: require('../../assets/data/chapters/zh/110.json'),
    111: require('../../assets/data/chapters/zh/111.json'),
    112: require('../../assets/data/chapters/zh/112.json'),
    113: require('../../assets/data/chapters/zh/113.json'),
    114: require('../../assets/data/chapters/zh/114.json'),
  },
};

export const getChapterData = (lang, chapterId) => {
  const langData = chapterMappings[lang] || chapterMappings['en'];
  return langData[chapterId] || chapterMappings['en'][chapterId];
};
